"""Offline orchestration probes; mocked input acceptance is not real-source evidence."""

import importlib.util
import json
from pathlib import Path
from types import SimpleNamespace

import pytest

SCRIPT = Path(__file__).resolve().parents[1] / "scripts/stage_acquired_slice.py"


@pytest.fixture
def script():
    spec = importlib.util.spec_from_file_location("stage_acquired_slice", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def paths(tmp_path):
    return {"acquisition_dir": tmp_path / "audit", "boundary": tmp_path / "boundary.zip",
            "document": tmp_path / "document.pdf", "data_dir": tmp_path / "new-data"}


@pytest.mark.parametrize("existing", ["empty", "old-store", "symlink"])
def test_existing_root_untouched_before_input_access(script, tmp_path, monkeypatch, existing):
    args = paths(tmp_path)
    root = args["data_dir"]
    if existing == "symlink":
        target = tmp_path / "earlier"
        target.mkdir()
        root.symlink_to(target, target_is_directory=True)
    else:
        root.mkdir()
    if existing == "old-store":
        (root / "baseline.sqlite").write_bytes(b"historical-ledger-sentinel")
    before = {p.name: p.read_bytes() for p in root.iterdir() if p.is_file()}
    monkeypatch.setattr(script, "read_acquisition", lambda **kw: pytest.fail("read input"))
    with pytest.raises(ValueError):
        script.stage_slice(**args)
    assert before == {p.name: p.read_bytes() for p in root.iterdir() if p.is_file()}


def test_invalid_bundle_creates_no_store(script, tmp_path, monkeypatch):
    args = paths(tmp_path)

    def fail(**kwargs):
        raise ValueError("Synthetic corrupt bundle")

    monkeypatch.setattr(script, "read_acquisition", fail)
    with pytest.raises(ValueError):
        script.stage_slice(**args)
    assert not args["data_dir"].exists()


@pytest.mark.parametrize("current_valid", [True, False])
def test_explicit_three_imports_and_current_revalidation(script, tmp_path, monkeypatch,
                                                      current_valid):
    """Mocks isolate orchestration, never certify generated bytes as live observations."""
    args = paths(tmp_path)
    args["boundary"].write_bytes(b"synthetic boundary")
    args["document"].write_bytes(b"synthetic document")
    accepted = SimpleNamespace(valid=True)
    monkeypatch.setattr(script, "read_acquisition", lambda **kw: SimpleNamespace(
        raw=b"synthetic ACS", retrieval=object(), spec_bytes=b"synthetic spec"))
    for name in ("normalize_acs", "normalize_boundaries", "normalize_document"):
        monkeypatch.setattr(script, name, lambda *a, **kw: accepted)
    monkeypatch.setattr(script, "validate_slice", lambda *a: accepted)
    calls = []

    def initialize(root):
        assert root == args["data_dir"] and root.is_dir()
        assert list(root.iterdir()) == []
        calls.append("init")

    class Staging:
        def __init__(self, root):
            assert root == args["data_dir"]

        def create_run(self, *, synthetic):
            assert synthetic is False
            calls.append("run")
            return "explicit-run"

        def stage(self, run, source, raw, retrieval, spec, *, synthetic):
            assert run == "explicit-run" and synthetic is False
            calls.append(source)
            return SimpleNamespace(import_id="selected-" + source)

    class Validation:
        def __init__(self, root):
            assert root == args["data_dir"]

        def validate(self, run, ids):
            assert run == "explicit-run"
            assert ids == ("selected-acs", "selected-boundary", "selected-document")
            calls.append("validate")
            current = calls.count("validate") == 2
            valid = current_valid if current else True
            pins = [SimpleNamespace(verified=valid, version_ids=("v",) * count)
                    for count in (225, 75, 3)]
            return SimpleNamespace(report_id="current" if current else "initial",
                                   content=SimpleNamespace(real_slice_valid=valid, inputs=pins))

        def read_report(self, *args):
            pytest.fail("Historical read is not current validation")

    monkeypatch.setattr(script, "initialize", initialize)
    monkeypatch.setattr(script, "CandidateStaging", Staging)
    monkeypatch.setattr(script, "CandidateValidation", Validation)
    result = script.stage_slice(**args)
    assert calls == ["init", "run", "acs", "boundary", "document", "validate", "validate"]
    assert result["current_real_slice_valid"] is current_valid
    assert result["initial_real_slice_valid"] is True
    assert result["current_verified_input_count"] == (3 if current_valid else 0)
    assert result["current_version_count"] == 303
    assert result["sealed"] is result["activated"] is False
    assert result["boundary_document_fresh_access"] is False


def test_incompatible_slice_stops_before_initialization(script, tmp_path, monkeypatch):
    args = paths(tmp_path)
    args["boundary"].write_bytes(b"synthetic invalid boundary")
    args["document"].write_bytes(b"synthetic invalid PDF")
    monkeypatch.setattr(script, "read_acquisition", lambda **kw: SimpleNamespace(
        raw=b"[]", retrieval=object(), spec_bytes=b""))
    monkeypatch.setattr(script, "normalize_acs", lambda *a, **kw: SimpleNamespace(valid=False))
    monkeypatch.setattr(script, "validate_slice", lambda *a: SimpleNamespace(valid=False))
    monkeypatch.setattr(script, "initialize", lambda *a: pytest.fail("initialized"))
    with pytest.raises(ValueError):
        script.stage_slice(**args)
    assert not args["data_dir"].exists()


def test_cli_failure_does_not_echo_source_or_paths(script, tmp_path, monkeypatch, capsys):
    def fail(**kwargs):
        raise ValueError("SYNTHETIC-SECRET-OR-SOURCE-TEXT")

    monkeypatch.setattr(script, "stage_slice", fail)
    args = [value for key, path in paths(tmp_path).items()
            for value in ("--" + key.replace("_", "-"), str(path))]
    assert script.main(args) == 2
    output = capsys.readouterr().out
    assert json.loads(output)["staged_and_verified"] is False
    assert "SYNTHETIC-SECRET-OR-SOURCE-TEXT" not in output
    assert str(tmp_path) not in output
